apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-secret
  name: busybox-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-secret
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox-secret
    spec:
      containers:
      - image: busybox
        name: busybox
        command: [ "/bin/sh","-c","echo ${USERNAME} > /bin/usr.txt; echo ${PASSWORD} > /bin/pss.txt; while true; do continue; done;" ]
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: vinitsecret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: vinitsecret
                key: password
status: {}
