version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: "postgres"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
      
  web:
    build: .
    container_name: "backend-app"
    command: ["go", "run", "main.go"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres:
networks:
  fullstack:
    driver: bridge