apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backendapp
spec:
  defaultBackend:
        service:
            name: backendapp-service
            port:
                number: 8080
